---
default_stages: [pre-commit]

default_install_hook_types: [pre-commit, commit-msg]
exclude: .*\.(patch)|(diff)$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.36.0
    hooks:
      - id: markdownlint
      - id: markdownlint-fix

  - repo: https://github.com/talos-systems/conform
    rev: v0.1.0-alpha.27
    hooks:
      - id: conform
        stages:
          - commit-msg

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]

  - repo: https://github.com/zarhus/oelint-adv
    rev: 5.5.2-zarhus
    hooks:
      - id: oelint-adv
        args: [--rulefile=.oelint-ruleset.json, --hide=info, --quiet, --fix]
        name: Advanced oelint
        description: Based on the OpenEmbedded Styleguide and work done by oe-stylize-tool this module offers a (nearly) complete linter for bitbake-recipes.
        entry: oelint-adv
        language: python
        language_version: python3
        files: .*\.(bb)|(bbappend)|(bbclass)$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell

  - repo: https://github.com/3mdeb/hooks
    rev: v0.1.2
    hooks:
      - id: namespell
        args: [--fix]
        exclude: meta-dts-distro/recipes-tests/converged-security-suite/bg-suite/bg-suite
ci:
  autoupdate_commit_msg: 'pre-commit: autoupdate hooks'
  autofix_prs: false
  # docker is not supported on pre-commit.ci
  skip: [shellcheck]
