require dts-sb-distro.conf

APPEND:remove = "quiet"

UEFI_SELOADER = "1"
GRUB_SIGN_VERIFY = "0"

IMAGE_EFI_BOOT_FILES = " \
    grubenv;EFI/BOOT/ \
    grub.cfg;EFI/BOOT/ \
    efi-unsigned/*.efi;EFI/BOOT/ \
    efi-unsigned/x86_64-efi/*;EFI/BOOT/x86_64-efi/ \
"
