#!/usr/bin/env bash

trap : 2
trap : 3

CMD_SHELL="/bin/bash"
#CMD_POWEROFF="/sbin/poweroff"
#CMD_REBOOT="/sbin/reboot"
CMD_EC_TRANSITION="/usr/sbin/ec_transition"

logs_sent=""

Cloud_base_url="https://cloud.3mdeb.com/index.php/s/"

# base values for CE


while : ; do
  echo "  1) Dasharo EC transition - perform full EC transition"
  echo "  9) Shell"
  echo "  10) Get back to main menu"
  echo
  read -p "Enter an option: " OPTION
  echo

  case ${OPTION} in
    1)
      echo "Attempting to perform full EC transition"
      ${CMD_EC_TRANSITION}
      ;;
    9)
      echo "Entering shell, to leave type exit and press Enter or press LCtrl+D"
      echo ""
      ${CMD_SHELL}
      ;;
    10)
      exit
      ;;
    *)
      ;;
  esac
done
