# NovaCustom heads keys
NCM_HEADS_LOGS_KEY=''
NCM_HEADS_DL_KEY=''
NCM_HEADS_PWD=''

# MSI heads keys
MSI_HEADS_LOGS_KEY=''
MSI_HEADS_DL_KEY=''
MSI_HEADS_PWD=''

# MSI UEFI keys
MSI_UEFI_LOGS_KEY=''
MSI_UEFI_DL_KEY=''
MSI_UEFI_PWD=''

# PC Engines SeaBIOS keys
PCE_SEABIOS_LOGS_KEY=''
PCE_SEABIOS_DL_KEY=''
PCE_SEABIOS_PWD=''

# PC Engines UEFI keys
PCE_UEFI_LOGS_KEY=''
PCE_UEFI_DL_KEY=''
PCE_UEFI_PWD=''
