#!/bin/bash
source /usr/sbin/des-credentials.sh

# QEMU does not support flashrom read/write yet, provide some basic mock to pass flashrom calls
export FLASHROM="/usr/sbin/flashrom-mock.sh"
export DASHARO_ECTOOL="/usr/sbin/dasharo-ectool-mock.sh"
# Skip HCL report in Dasharo deployment, which takes a lot of time
# and creates many reports in cloud.
export LOGS_SENT="1"

CLOUD_PASS_FILE="/etc/cloud-pass"

if [ $TEST_DES == "y" ]; then
  rm -f "${CLOUD_PASS_FILE}"
  if [ "$BOARD_VENDOR" = "Notebook" ] && [ "$DES_TYPE" = "heads" ]; then
    echo "$NCM_HEADS_LOGS_KEY" >> "${CLOUD_PASS_FILE}"
    echo "$NCM_HEADS_DL_KEY" >> "${CLOUD_PASS_FILE}"
    echo "$NCM_HEADS_PWD" >> "${CLOUD_PASS_FILE}"
  elif [ "$BOARD_VENDOR" = "Micro-Star International Co., Ltd." ] && [ "$DES_TYPE" = "heads" ]; then
    echo "$MSI_HEADS_LOGS_KEY" >> "${CLOUD_PASS_FILE}"
    echo "$MSI_HEADS_DL_KEY" >> "${CLOUD_PASS_FILE}"
    echo "$MSI_HEADS_PWD" >> "${CLOUD_PASS_FILE}"
  elif [ "$BOARD_VENDOR" = "Micro-Star International Co., Ltd." ] && [ "$DES_TYPE" = "UEFI" ]; then
    echo "$MSI_UEFI_LOGS_KEY" >> "${CLOUD_PASS_FILE}"
    echo "$MSI_UEFI_DL_KEY" >> "${CLOUD_PASS_FILE}"
    echo "$MSI_UEFI_PWD" >> "${CLOUD_PASS_FILE}"
  elif [ "$BOARD_VENDOR" = "PC Engines" ] && [ "$DES_TYPE" = "UEFI" ]; then
    echo "$PCE_UEFI_LOGS_KEY" >> "${CLOUD_PASS_FILE}"
    echo "$PCE_UEFI_DL_KEY" >> "${CLOUD_PASS_FILE}"
    echo "$PCE_UEFI_PWD" >> "${CLOUD_PASS_FILE}"
  elif [ "$BOARD_VENDOR" = "PC Engines" ] && [ "$DES_TYPE" = "seabios" ]; then
    echo "$PCE_SEABIOS_LOGS_KEY" >> "${CLOUD_PASS_FILE}"
    echo "$PCE_SEABIOS_DL_KEY" >> "${CLOUD_PASS_FILE}"
    echo "$PCE_SEABIOS_PWD" >> "${CLOUD_PASS_FILE}"
  fi
elif [ $TEST_DES != "y" ] && [ -f "${CLOUD_PASS_FILE}" ]; then
  rm -f "${CLOUD_PASS_FILE}"
fi

if [ -f /tmp/bios.bin ]; then
  rm /tmp/bios.bin
fi

wget https://dl.3mdeb.com/open-source-firmware/Dasharo/novacustom_nv4x_adl/v1.7.2/novacustom_nv4x_adl_v1.7.2.rom -O /tmp/bios.bin

# export DTS_FUNCS="$PWD/../meta-dts-distro/recipes-dts/dts/dts/dts-functions.sh"
# export DTS_ENV="$PWD/dts-environment.sh"

export HAVE_EC="false"

source dts
