#!/usr/bin/expect -f

# export the right variables, then run the script
set env(BOARD_VENDOR) "Notebook"
set env(SYSTEM_MODEL) "NV4xPZ"
set env(BOARD_MODEL) "NV4xPZ"
set env(BIOS_VERSION) "Dasharo (coreboot+UEFI) v1.7.2"
set env(TEST_DES) "y"

# remember the PID so we can kill it when we are done
set DTSPID [spawn bash dts-boot]

# enter "Check and apply Dasharo firmware updates" option
expect "Enter an option: "
send "5\r"

# agree to switch to Dasharo heads firmware
expect "Would you like to switch to Dasharo heads firmware? (Y|n) "
send "Y\r"

# update
expect "Are you sure you want to proceed with update? (Y|n) "
send "Y\r"

# verify specification
expect "Does it match your actual specification? (Y|n) "
send "Y\r"

# final agreement to update
expect "Do you want to update Dasharo firmware on your hardware? (Y|n) "
send "Y\r"

expect "Press any key to continue"
send "\r"

# since we are done we can kill the script
expect "Enter an option: "
exec kill -9 $DTSPID

expect eof
