#!/usr/bin/expect -f

proc lookfor {pat} {
    expect timeout { send_user "timeout looking for '$pat'\r\n" ; exit } $pat
}

# export the right variables, then run the script
set env(BOARD_VENDOR) "Notebook"
set env(SYSTEM_MODEL) "NV4xPZ"
set env(BOARD_MODEL) "NV4xPZ"
set env(BIOS_VERSION) "Dasharo (coreboot+UEFI) v1.7.2"
set env(TEST_DES) "y"

# remember the PID so we can kill it when we are done
set DTSPID [spawn bash dts-boot]

# enter "Check and apply Dasharo firmware updates" option
lookfor "Enter an option: "
send "5\r"

# agree to switch to Dasharo heads firmware
lookfor "Would you like to switch to Dasharo heads firmware? (Y|n) "
send "Y\r"

# update
lookfor "Are you sure you want to proceed with update? (Y|n) "
send "Y\r"

# verify specification
lookfor "Does it match your actual specification? (Y|n) "
send "Y\r"

# final agreement to update
lookfor "Do you want to update Dasharo firmware on your hardware? (Y|n) "
send "Y\r"

lookfor "Press any key to continue"
send "\r"

# since we are done we can kill the script
lookfor "Enter an option: "
exec kill -9 $DTSPID

lookfor eof
