#!/usr/bin/env bash

source /usr/sbin/dts-environment.sh
source /usr/sbin/dts-functions.sh

trap : 2
trap : 3

CMD_DASHARO_HCL_REPORT="/usr/sbin/dasharo-hcl-report"
CMD_SHELL="/bin/bash"
CMD_REBOOT="/sbin/reboot"
CMD_NCMENU="/usr/sbin/novacustom_menu"
CMD_DASHARO_DEPLOY="/usr/sbin/dasharo-deploy"

OS_VERSION_FILE="/etc/os-release"

SE_credential_file="/etc/cloud-pass"

check_os_version() {
  local os_version=$(grep "VERSION_ID" ${OS_VERSION_FILE} | cut -d "=" -f 2-)

  if [ ${SE_IS_LOGGED} ]; then
    echo "  Logs key:        " ${CLOUDSEND_LOGS_URL}
    echo "  Download key:    " ${CLOUDSEND_DOWNLOAD_URL}
    echo "  Password:        " ${CLOUDSEND_PASSWORD}
  fi
  echo "  DTS version v${os_version}"
}

print_disclaimer() {
echo -e \
"Please note that the report is not anonymous, but we will use it only for\r
backup and future improvement of the Dasharo product. Every log is encrypted\r
and sent over HTTPS, so security is assured.\r
If you still have doubts, you can skip HCL report generation.\r\n
What is inside the HCL report? We gather information about:\r
  - PCI, Super I/O, GPIO, EC, audio, and Intel configuration,\r
  - MSRs, CMOS NVRAM, CPU info, DIMMs, state of touchpad, SMBIOS and ACPI tables,\r
  - Decoded BIOS information, full firmware image backup, kernel dmesg,\r
  - IO ports, input bus types, and topology - including I2C and USB,\r
\r
You can find more info about HCL in docs.dasharo.com/glossary\r"
}

print_banner() {
echo '    ____             __                        ______            __        _____       _ __'
echo '   / __ \____ ______/ /_  ____ __________     /_  __/___  ____  / /____   / ___/__  __(_) /'____
echo '  / / / / __ `/ ___/ __ \/ __ `/ ___/ __ \     / / / __ \/ __ \/ / ___/   \__ \/ / / / / __/ _ \'
echo ' / /_/ / /_/ (__  ) / / / /_/ / /  / /_/ /    / / / /_/ / /_/ / (__  )   ___/ / /_/ / / /_/  __/'
echo '/_____/\__,_/____/_/ /_/\__,_/_/   \____/    /_/  \____/\____/_/____/   /____/\__,_/_/\__/\___/'
echo
}

check_network_connection() {
  echo 'Waiting for network connection ...'
  n="5"
  while : ; do
    ping -c 3 cloud.3mdeb.com > /dev/null 2>&1 && break
    n=$((n-1))
    if [ "${n}" == "0" ]; then
      echo 'No network connection to 3mdeb cloud, please recheck Ethernet connection'
      return 1
    fi
    sleep 1
  done
  return 0
}

vendor_menu()
{
  case "$BOARD_VENDOR" in
    "Notebook")
      case "$SYSTEM_MODEL" in
      "NV4XMB,ME,MZ" | "NS50_70MU")
        case "$1" in
          "print")
             echo "  6) NovaCustom menu"
            ;;
          "action")
            echo "Entering NovaCustom menu, to leave type exit and press Enter or press LCtrl+D"
            echo ""
            ${CMD_NCMENU}
            ;;
          *)
            ;;
        esac
        ;;
      *)
        ;;
      esac
  esac
}

print_banner

logs_sent=""

Cloud_base_url="https://cloud.3mdeb.com/index.php/s/"

# base values
export CLOUDSEND_LOGS_URL="39d4biH4SkXD8Zm"
export CLOUDSEND_PASSWORD="1{\[\k6G"

if [ -a "${SE_credential_file}" ]; then
    export CLOUDSEND_LOGS_URL=$(head -1 ${SE_credential_file})
    export CLOUDSEND_DOWNLOAD_URL=$(head -2 ${SE_credential_file} | tail -1 )
    export CLOUDSEND_PASSWORD=$(head -3 ${SE_credential_file} | tail -1 )
    export SE_IS_LOGGED=true
fi

while : ; do
  echo
  check_os_version
  echo
  echo "  1) Dasharo HCL report - dump hardware information from this device"
  if ! check_if_dasharo; then
    echo "  2) Install Dasharo firmware"
  fi
  if check_if_dasharo; then
    echo "  3) Restore firmware from Dasharo HCL report"
  fi
  if [ -n "${SE_IS_LOGGED}" ]; then
      echo "  4) Edit SE keys"
      echo "  5) Update Dasharo firmware"
  else
      echo "  4) Load SE keys"
  fi

  vendor_menu "print"
  echo "  9) Shell"
  echo "  10) Power off system"
  echo "  11) Reboot system"
  echo
  read -p "Enter an option: " OPTION
  echo

  case ${OPTION} in
    1)
      print_disclaimer
      read -p "Do you want to support Dasharo development by sending us logs with hardware configuration? [N/y] "
      case ${REPLY} in
          yes|y|Y|Yes|YES)
          export SEND_LOGS="true"
          echo "Thank you for contributing to the Dasharo development! "
          ;;
          *)
          export SEND_LOGS="false"
          echo "Logs will be saved in root directory."
          echo "Please consider supporting Dasharo by sending the logs next time."
          ;;
      esac
      if [ "${SEND_LOGS}" == "true" ]; then
          check_network_connection && ${CMD_DASHARO_HCL_REPORT} && logs_sent="1"
      else
          ${CMD_DASHARO_HCL_REPORT}
      fi
      ;;
    2)
      if ! check_if_dasharo; then
        if check_network_connection; then
          echo "Preparing ..."
          if [ -z "${logs_sent}" ]; then
            export SEND_LOGS="true"
            if ! ${CMD_DASHARO_HCL_REPORT} > /dev/null 2>&1; then
              echo -e "Cannot reach 3mdeb cloud to leave HCL report. Please
                        \rrecheck your internet connection."
            else
              logs_sent="1"
            fi
          fi
        fi
      fi

      if [ -n "${logs_sent}" ]; then
          ${CMD_DASHARO_DEPLOY} install
      fi
      ;;
    3)
      if check_if_dasharo; then
        ${CMD_DASHARO_DEPLOY} restore
      fi
      ;;
    4)
      echo ""
      read -p "Enter logs key:                " tmpUPURL
      echo ""
      read -p "Enter firmware download key:   " tmpDOWNLOADURL
      echo ""
      read -p "Enter password:                " tmpPASSWD

      echo ${tmpUPURL} > ${SE_credential_file}
      echo ${tmpDOWNLOADURL} >> ${SE_credential_file}
      echo ${tmpPASSWD} >> ${SE_credential_file}

      tmpDownloadURL="https://cloud.3mdeb.com/public.php/webdav/biosupdate.rom"

      tmpLogsURL="https://cloud.3mdeb.com/index.php/s/${CLOUDSEND_LOGS_URL}/authenticate/showShare"

      CLOUD_DOWNLOAD_URL=`sed -n '2p' < ${SE_credential_file} | tr -d '\n'`
      CLOUD_PASSWORD=`sed -n '3p' < ${SE_credential_file} | tr -d '\n'`
      USER_DETAILS="$CLOUD_DOWNLOAD_URL:$CLOUD_PASSWORD"
      CLOUD_REQUEST="X-Requested-With: XMLHttpRequest"

      if check_network_connection; then
        CHECK_DOWNLOAD_REQUEST_RESPONSE=$( curl -I -s -f -u "$USER_DETAILS" -H "$CLOUD_REQUEST" "$tmpDownloadURL" -o /dev/null -w "%{http_code}")
        CHECK_LOGS_REQUEST_RESPONSE=$( curl -I -s -f -H "$CLOUD_REQUEST" "$tmpLogsURL" -o /dev/null -w "%{http_code}")
        if [ ${CHECK_DOWNLOAD_REQUEST_RESPONSE} -eq 200 ] && [ ${CHECK_LOGS_REQUEST_RESPONSE} -eq 200 ]; then
          echo ""
          echo "Cloud credentials are saved and ready to use"
          export SE_IS_LOGGED=true
          export CLOUDSEND_PASSWORD="${tmpPASSWD}"
          export CLOUDSEND_LOGS_URL="${tmpUPURL}"
          export CLOUDSEND_DOWNLOAD_URL="${tmpDOWNLOADURL}"
        else
          echo ""
          echo -e "Something may be wrong with credentials. Please use option 4 to change SE keys
                    \rand make sure that there is no typo."
          rm ${SE_credential_file}
        fi
      fi
      ;;
    5)
      echo "There is no Dasharo firmware update available now for your platform"
      read -r -p "Please, type any key to back to main menu " OPTION
      echo

      case ${OPTION} in
        *)
          echo "Returning to main menu..."
          exit 0
          ;;
      esac
      ;;
    6)
      vendor_menu "action"
      ;;
    9)
      echo "Entering shell, to leave type exit and press Enter or press LCtrl+D"
      echo ""
      ${CMD_SHELL}
      ;;
    10)
      ${CMD_POWEROFF}
      ;;
    11)
      ${CMD_REBOOT}
      ;;
    *)
      ;;
  esac
done
