name: CI
on:
  push:
    branches:
      - builder

jobs:
  build:
    name: Build system image
    runs-on: self-hosted
    steps:
      - name: Checkout meta-dts-ce repo
        uses: actions/checkout@v2
        with:
          path: "meta-dts-ce"
