name: CI on push tag
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build system image
    runs-on: self-hosted
    steps:
      - name: Checkout meta-dts repo
        uses: actions/checkout@v2
        with:
          path: "meta-dts"
      - name: Build DTS image
        shell: bash
        run: |
          kas-container build meta-dts/kas.yml
  deploy-images:
    name: Deploy DTS artifacts on boot.dasharo.com
    if: always()
    needs: build
    runs-on: self-hosted
    steps:
      - name: Prepare SSH key
        shell: bash
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}
        run: |
          echo -e ${SSH_KEY} | sed 's/^ *//' > ~/.ssh/dts-ci-key
          chmod 600 ~/.ssh/dts-ci-key
      - name: Get DTS version
        id: dts-ver
        shell: bash
        run: |
          DTS_VER=`cat meta-dts/meta-dts-distro/conf/distro/dts-distro.conf | grep DISTRO_VERSION | tr -d "\" [A-Z]_="`
          echo "DTS_VER=${DTS_VER}" >> $GITHUB_OUTPUT
      - name: Deploy DTS on boot.dasharo.com
        shell: bash
        run: |
          DTS_VER="${{steps.dts-ver.outputs.DTS_VER}}"
          ssh -i ~/.ssh/dts-ci-key builder@10.1.40.2 "mkdir -p boot/dts/${DTS_VER}"
          cd build/tmp/deploy/images/genericx86-64/
          cp bzImage bzImage-${DTS_VER}
          cp dts-base-image-genericx86-64.cpio.gz dts-base-image-${DTS_VER}.cpio.gz
          cp dts-base-image-genericx86-64.wic.gz dts-base-image-${DTS_VER}.wic.gz
          scp -i ~/.ssh/dts-ci-key bzImage-${DTS_VER} builder@10.1.40.2:boot/dts/${DTS_VER}/
          scp -i ~/.ssh/dts-ci-key dts-base-image-${DTS_VER}.cpio.gz builder@10.1.40.2:boot/dts/${DTS_VER}/
          scp -i ~/.ssh/dts-ci-key dts-base-image-${DTS_VER}.wic.gz builder@10.1.40.2:boot/dts/${DTS_VER}/
      - name: Deploy sha256 on boot.dasharo.com
        shell: bash
        run: |
          DTS_VER="${{steps.dts-ver.outputs.DTS_VER}}"
          cd build/tmp/deploy/images/genericx86-64/
          sha256sum bzImage-${DTS_VER} > bzImage-${DTS_VER}.sha256
          sha256sum dts-base-image-${DTS_VER}.cpio.gz > dts-base-image-${DTS_VER}.cpio.gz.sha256
          sha256sum dts-base-image-${DTS_VER}.wic.gz > dts-base-image-${DTS_VER}.wic.gz.sha256
          scp -i ~/.ssh/dts-ci-key bzImage-${DTS_VER}.sha256 builder@10.1.40.2:boot/dts/${DTS_VER}/
          scp -i ~/.ssh/dts-ci-key dts-base-image-${DTS_VER}.cpio.gz.sha256 builder@10.1.40.2:boot/dts/${DTS_VER}/
          scp -i ~/.ssh/dts-ci-key dts-base-image-${DTS_VER}.wic.gz.sha256 builder@10.1.40.2:boot/dts/${DTS_VER}/
      - name: Update iPXE menu
        shell: bash
        run: |
          ./meta-dts/scripts/generate-ipxe-menu.sh ${{steps.dts-ver.outputs.DTS_VER}}
          scp -i ~/.ssh/dts-ci-key dts.ipxe builder@10.1.40.2:boot/dts/
  cleanup:
    name: Cleanup
    if: always()
    needs: deploy-images
    runs-on: self-hosted
    steps:
      - name: Cleanup after deployment
        shell: bash
        run: |
          rm -rf ~/.ssh/dts-ci-key
          rm -rf build
