---
name: Run DTS tests
on:
  pull_request:
    branches:
      - "main"
jobs:
  build-dts:
    uses: ./.github/workflows/build.yml
    with:
      cacheless: false

  run-tests:
    name: Run DTS tests
    needs: build-dts
    runs-on:
      labels: dts-builder
    strategy:
      matrix:
        include:
          - test: msi_comm
            dpp_download_key: $MSI_DOWNLOAD
            dpp_logs_key: $MSI_LOGS
            log_file: output_msi.log

          - test: msi_dpp
            dpp_download_key: $MSI_DOWNLOAD
            dpp_logs_key: $MSI_LOGS
            log_file: output_msi.log

          - test: msi_heads
            dpp_download_key: $MSI_HEADS_DOWNLOAD
            dpp_logs_key: $MSI_HEADS_LOGS
            log_file: output_msi_heads.log

          - test: optiplex_dpp
            dpp_download_key: $OPTIPLEX_DOWNLOAD
            dpp_logs_key: $OPTIPLEX_LOGS
            log_file: output_nc_heads.log

          - test: novacustom_heads
            dpp_download_key: $OPTIPLEX_DOWNLOAD
            dpp_logs_key: $OPTIPLEX_LOGS
            log_file: output_nc_heads.log

          - test: novacustom_comm
            dpp_download_key: $OPTIPLEX_DOWNLOAD
            dpp_logs_key: $OPTIPLEX_LOGS
            log_file: output_nc_heads.log

          - test: pcengines_dpp
            dpp_download_key: $PCENGINES_DOWNLOAD
            dpp_logs_key: $PCENGINES_LOGS
            log_file: output_pcengines.log

          - test: pcengines_seabios
            dpp_download_key: $PCENGINES_SEABIOS_DOWNLOAD
            dpp_logs_key: $PCENGINES_SEABIOS_LOGS
            log_file: output_pcengines_seabios.log

    steps:
      - name: Checkout OSFV repo
        uses: actions/checkout@v4
        with:
          repository: "Dasharo/open-source-firmware-validation"
          path: "open-source-firmware-validation"
          submodules: "recursive"
          ref: "develop"

      - name: Run IPXE server
        shell: bash
        run: ./open-source-firmware-validation/scripts/ci/ipxe-run.sh \
          build/tmp/deploy/images/genericx86-64/dts-base-image-genericx86-64.cpio.gz \
          build/tmp/deploy/images/genericx86-64/bzImage

      - name: Install requirements
        shell: bash
        run: |
          cd open-source-firmware-validation
          python3 -m virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run QEMU
        shell: bash
        id: run_qemu
        run: |
          cd open-source-firmware-validation/scripts/ci
          mkdir qemu-data
          touch qemu-data/hdd.qcow2
          ./qemu-run.sh nographic os &

      - name: Create directory for logs
        shell: bash
        id: create_log_dirs
        run: |
          export LOG_DIR="/tmp/dst-test-ci-${{ github.run_id }}/${{ matrix.include.test }}"
          mkdir -p $LOG_DIR
          echo "LOG_DIR=$LOG_DIR" >> $GITHUB_ENV

      - name: Run ${{ matrix.include.test }}
        shell: bash
        env:
          LOG_DIR: ${{ steps.log_dirs.outputs.directory }}
        run: |
          cd open-source-firmware-validation
          source venv/bin/activate
          # This file is already present on dts-builder.
          # It contains credentials for DPP subscriptions.
          # It has the following form:
          # DPP_PASSWORD="..."
          # <SUBSCRIPTION_TYPE>_DOWNLOADS="download key"
          # <SUBSCRIPTION_TYPE>_LOGS="logs key"
          # (...)
          source ~/.secrets/dpp-keys
          ip_addr=$(ip -o -4 addr list eno2 | awk '{print $4}' | cut -d/ -f1)

          ./scripts/run.sh -L TRACE -v config:qemu -v rte_ip:127.0.0.1 -v snipeit:no \
          -v dpp_password:$DPP_PASSWORD -v dpp_download_key:${{ matrix.include.dpp_download_key }} \
          -v dpp_logs_key:${{ matrix.include.dpp_logs_key }} -v netboot_utilities_support:True \
          -v dts_ipxe_link:http://${ip_addr}:4321/dts.ipxe \
          -i ${{ matrix.include.test }} dts/dts-e2e.robot 2>&1 \
          | tee $LOG_DIR/${{ matrix.include.log_file }} | grep "| PASS |\|| FAIL |"

      - name: Copy log
        shell: bash
        if: ${{ !cancelled() }}
        env:
          LOG_DIR: ${{ steps.log_dirs.outputs.directory }}
        run: |
          cp open-source-firmware-validation/log.html $LOG_DIR/log.html

  cleanup:
    name: Cleanup
    if: always()
    needs: run-tests
    runs-on:
      labels: dts-builder
    steps:
      - name: Cleanup after tests
        shell: bash
        run: |
          rm -rf open-source-firmware-validation meta-dts build ipxe
